# Generated by Django 2.2 on 2020-11-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_comment_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborator',
            name='range',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
