# Generated by Django 2.2 on 2020-11-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201121_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
