# Generated by Django 2.2 on 2020-11-17 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_comment_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Collaborator')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'storyroute',
            },
        ),
        migrations.CreateModel(
            name='OrderByRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('story_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories_routes.OrderByRoute')),
                ('story_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories_routes.StoryRoute')),
            ],
            options={
                'db_table': 'order_route',
            },
        ),
    ]
