# Generated by Django 2.2 on 2020-11-20 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyroute',
            name='collaborator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Collaborator'),
        ),
    ]
