# Generated by Django 2.2 on 2020-11-23 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories_routes', '0003_auto_20201123_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbyroute',
            name='story_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories_routes.StoryRoute'),
        ),
    ]
