# Generated by Django 2.2 on 2020-11-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories_routes', '0004_auto_20201123_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbyroute',
            old_name='story_position',
            new_name='story_child',
        ),
    ]
