# Generated by Django 2.2 on 2020-11-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories_routes', '0006_auto_20201123_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbyroute',
            old_name='story_parent',
            new_name='story_child',
        ),
    ]
