# Generated by Django 2.2 on 2020-11-17 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories_routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hopscotch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=511)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('hopscotch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hopscotch.Hopscotch')),
                ('story_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stories_routes.StoryRoute')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
            options={
                'db_table': 'hashtag',
            },
        ),
    ]
